assembliesFilter: -:Unity*;-:com.unity*;-:Cinemachine;-:CustomEditor;-:YamlDotNet*
reportAbsolutePath: C:\Users\Yukiix\UnityCI\dotCover\master\91dade0313c1eae4ceffe41cb79fedc1acf61571-20231017_17_57_07
samples:
- CustomUpdateRun
- Factorial

