

POST https://github.com/login/oauth/access_token
Content-Type: application/json
Accept: application/json

{
  "client_id": "5ff277c3ed80e122d347",
  "client_secret": "90a0181c49f2449ec65fc6ed5cd831d5fef82fd4",
  "code": "7edf735fed4971e9cd4e"
}