name: Unity CI IOS Test

on: 
  workflow_dispatch:
  push:
      paths:
        - '.github/workflows/iosTest.yml'
jobs:
  testManualBuild:
    name: ManualBuildIOS
    runs-on: ubuntu-latest
    container: 
      image: unityci/editor:ubuntu-2023.1.3f1-ios-1.1.2
      env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_LICENSE_BASE64: ${{ secrets.UNITY_LICENSE_BASE64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a command in Docker container
        run: |
          unity-editor -version
          ls -al
          echo === GITHUB ENV ===
          echo $UNITY_LICENSE
          echo === BASE64 ===
          echo $UNITY_LICENSE_BASE64
          echo === DECODED ====
          echo $UNITY_LICENSE_BASE64 | base64 --decode
          echo $UNITY_LICENSE_BASE64 | base64 --decode > license2.ulf
          ls -al
          echo === LICENSE 1 working ===
          cat license.ulf
          echo === LICENSE 2 from env ===
          cat license2.ulf
          unity-editor -batchmode -quit -manualLicenseFile license2.ulf -logFile /dev/stdout
          unity-editor -batchmode -quit -createProject '$(pwd)' -logFile /dev/stdout
          ls -la
