name: Unity CI IOS Test

on: 
  workflow_dispatch:

jobs:
  testManualBuild:
    name: ManualBuildIOS
    runs-on: ubuntu-latest
    container: 
      image: unityci/editor:ubuntu-2023.1.3f1-ios-1.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
      - name: Run a command in Docker container
        run: |
          echo Testing unityci/editor:ubuntu-2023.1.3f1-ios-1.1.2
          unity-editor -batchmode -logFile -
