name: Unity CI IOS Test

on: 
  workflow_dispatch:
  push:
      paths:
        - '.github/workflows/iosTest.yml'
jobs:
  testManualBuild:
    name: ManualBuildIOS
    runs-on: ubuntu-latest
    container: 
      image: unityci/editor:ubuntu-2023.1.3f1-ios-1.1.2
      env:
          UNITY_LICENSE_BASE64: ${{secrets. UNITY_LICENSE_BASE64}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a command in Docker container
        run: |
          unity-editor -version
          echo $UNITY_LICENSE_BASE64 | base64 --decode > license.ulf
          ls -al
          unity-editor -batchmode -quit -manualLicenseFile license.ulf -logFile /dev/stdout
          unity-editor -batchmode -quit -createProject '$(pwd)' -logFile /dev/stdout
          unity-editor -batchmode -executeMethod Editor.BuildIosSimulator.BuildIos -logFile /dev/stdout
          ls -la
