name: Self-hosted Runner Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - main # Replace with the branch name you want to trigger on
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run a command in Docker container
        run: Get-Command unity.exe | Select-Object -ExpandProperty Source
      - name: list
        run: dir
      - name: Generate Project
        run: unity -batchmode -projectPath . -logfile -

  cleanup:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: cleanup
        run: rm -r -- !(.) .*
