name: Build web

on:
  push:
    paths:
      - 'Web/**'
      - '.github/workflows/web.yml'
    branches:
      - master

jobs:
  build_gh-pages:
    name: Build React App 📦
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install dependencies
        working-directory: ./Web/unity-ci
        run: npm ci
      - name: build app
        working-directory: ./Web/unity-ci
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./Web/unity-ci/build  # Adjust the path to your build folder
